spring:
  application:
    name: team-02
  profiles:
    active: dev
  http:
    client:
      connect-timeout: 3s
      read-timeout: 10s
  config:
    import: optional:classpath:application-secret.yml
