spring:
  application:
    name: team-02

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  http:
    client:
      connect-timeout: 3s
      read-timeout: 10s

  config:
    import: optional:classpath:application-secret.yml

  jpa:
    open-in-view: false