spring:
  application:
    name: team-02
  http:
    client:
      connect-timeout: 3s
      read-timeout: 5s
  config:
    import: optional:classpath:application-secret.yml

  profiles:
    active: dev