-- 과거 복수형 테이블 제거
DROP TABLE IF EXISTS "sync_jobs";
DROP TABLE IF EXISTS "auto_sync_configs";
DROP TABLE IF EXISTS "index_infos";

-- 현재 단수형 테이블 제거
DROP TABLE IF EXISTS "sync_job";
DROP TABLE IF EXISTS "auto_sync_config";
DROP TABLE IF EXISTS "index_data";
DROP TABLE IF EXISTS "index_info";


CREATE TABLE "index_info" (
                              "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                              "index_classification" VARCHAR NOT NULL,
                              "index_name" VARCHAR NOT NULL,
                              "employed_items_count" INTEGER NOT NULL,
                              "base_point_in_time" DATE NOT NULL,
                              "base_index" DECIMAL(10, 2) NOT NULL,
                              "source_type" VARCHAR NOT NULL,
                              "favorite" BOOLEAN NOT NULL,
                              "created_at" TIMESTAMP NOT NULL,
                              "updated_at" TIMESTAMP NOT NULL,

                              CONSTRAINT "PK_INDEX_INFO"
                                  PRIMARY KEY ("id"),

                              CONSTRAINT "UK_INDEX_INFO_CLASSIFICATION_NAME"
                                  UNIQUE ("index_classification", "index_name"),

                              CONSTRAINT "CK_INDEX_INFO_EMPLOYED_ITEMS_COUNT"
                                  CHECK ("employed_items_count" >= 0),

                              CONSTRAINT "CK_INDEX_INFO_BASE_INDEX"
                                  CHECK ("base_index" >= 0)
);


CREATE TABLE "index_data" (
                              "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                              "index_info_id" BIGINT NOT NULL,
                              "base_date" DATE NOT NULL,
                              "source_type" VARCHAR NOT NULL,
                              "market_price" DECIMAL(10, 2) NOT NULL,
                              "closing_price" DECIMAL(10, 2) NOT NULL,
                              "high_price" DECIMAL(10, 2) NOT NULL,
                              "low_price" DECIMAL(10, 2) NOT NULL,
                              "versus" DECIMAL(10, 2) NOT NULL,
                              "fluctuation_rate" DECIMAL(10, 2) NOT NULL,
                              "trading_quantity" BIGINT NOT NULL,
                              "trading_price" BIGINT NOT NULL,
                              "market_total_amount" BIGINT NOT NULL,
                              "created_at" TIMESTAMP NOT NULL,
                              "updated_at" TIMESTAMP NOT NULL,

                              CONSTRAINT "PK_INDEX_DATA"
                                  PRIMARY KEY ("id"),

                              CONSTRAINT "FK_INDEX_DATA_INDEX_INFO"
                                  FOREIGN KEY ("index_info_id")
                                      REFERENCES "index_info" ("id")
                                      ON DELETE CASCADE,

                              CONSTRAINT "UK_INDEX_DATA_INDEX_INFO_BASE_DATE"
                                  UNIQUE ("index_info_id", "base_date"),

                              CONSTRAINT "CK_INDEX_DATA_MARKET_PRICE"
                                  CHECK ("market_price" >= 0),

                              CONSTRAINT "CK_INDEX_DATA_CLOSING_PRICE"
                                  CHECK ("closing_price" >= 0),

                              CONSTRAINT "CK_INDEX_DATA_HIGH_PRICE"
                                  CHECK ("high_price" >= 0),

                              CONSTRAINT "CK_INDEX_DATA_LOW_PRICE"
                                  CHECK ("low_price" >= 0),

                              CONSTRAINT "CK_INDEX_DATA_TRADING_QUANTITY"
                                  CHECK ("trading_quantity" >= 0),

                              CONSTRAINT "CK_INDEX_DATA_TRADING_PRICE"
                                  CHECK ("trading_price" >= 0),

                              CONSTRAINT "CK_INDEX_DATA_MARKET_TOTAL_AMOUNT"
                                  CHECK ("market_total_amount" >= 0)
);


CREATE TABLE "auto_sync_config" (
                                    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                    "index_info_id" BIGINT NOT NULL,
                                    "enabled" BOOLEAN NOT NULL,
                                    "created_at" TIMESTAMP NOT NULL,
                                    "updated_at" TIMESTAMP NOT NULL,

                                    CONSTRAINT "PK_AUTO_SYNC_CONFIG"
                                        PRIMARY KEY ("id"),

                                    CONSTRAINT "FK_AUTO_SYNC_CONFIG_INDEX_INFO"
                                        FOREIGN KEY ("index_info_id")
                                            REFERENCES "index_info" ("id")
                                            ON DELETE CASCADE,

                                    CONSTRAINT "UK_AUTO_SYNC_CONFIG_INDEX_INFO"
                                        UNIQUE ("index_info_id")
);


CREATE TABLE "sync_job" (
                            "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

    -- 지수 정보 삭제 시 NULL로 변경해야 하므로 nullable
                            "index_info_id" BIGINT NULL,

                            "target_date" DATE NULL,
                            "worker" VARCHAR NOT NULL,
                            "job_time" TIMESTAMP NOT NULL,
                            "result" VARCHAR NOT NULL,
                            "created_at" TIMESTAMP NOT NULL,
                            "updated_at" TIMESTAMP NOT NULL,
                            "job_type" VARCHAR NOT NULL,

                            CONSTRAINT "PK_SYNC_JOB"
                                PRIMARY KEY ("id"),

                            CONSTRAINT "FK_SYNC_JOB_INDEX_INFO"
                                FOREIGN KEY ("index_info_id")
                                    REFERENCES "index_info" ("id")
                                    ON DELETE SET NULL,

                            CONSTRAINT "CK_SYNC_JOB_RESULT"
                                CHECK ("result" IN ('SUCCESS', 'FAILED')),

                            CONSTRAINT "CK_SYNC_JOB_JOB_TYPE"
                                CHECK ("job_type" IN ('INDEX_INFO', 'INDEX_DATA'))
);


COMMENT ON COLUMN "index_info"."index_classification"
    IS '지수 분류';

COMMENT ON COLUMN "index_info"."index_name"
    IS '지수명';

COMMENT ON COLUMN "index_info"."employed_items_count"
    IS '포함 종목 수';

COMMENT ON COLUMN "index_info"."base_point_in_time"
    IS '기준 시점';

COMMENT ON COLUMN "index_info"."base_index"
    IS '기준 지수';

COMMENT ON COLUMN "index_info"."source_type"
    IS '데이터 출처';

COMMENT ON COLUMN "index_info"."favorite"
    IS '즐겨찾기';


COMMENT ON COLUMN "index_data"."index_info_id"
    IS '지수 정보 ID';

COMMENT ON COLUMN "index_data"."base_date"
    IS '기준일';

COMMENT ON COLUMN "index_data"."source_type"
    IS '데이터 출처';

COMMENT ON COLUMN "index_data"."market_price"
    IS '시장가';

COMMENT ON COLUMN "index_data"."closing_price"
    IS '종가';

COMMENT ON COLUMN "index_data"."high_price"
    IS '고가';

COMMENT ON COLUMN "index_data"."low_price"
    IS '저가';

COMMENT ON COLUMN "index_data"."versus"
    IS '전일 대비';

COMMENT ON COLUMN "index_data"."fluctuation_rate"
    IS '등락률';

COMMENT ON COLUMN "index_data"."trading_quantity"
    IS '거래량';

COMMENT ON COLUMN "index_data"."trading_price"
    IS '거래대금';

COMMENT ON COLUMN "index_data"."market_total_amount"
    IS '시가총액';


COMMENT ON COLUMN "auto_sync_config"."index_info_id"
    IS '지수 정보 ID';

COMMENT ON COLUMN "auto_sync_config"."enabled"
    IS '자동 연동 활성화 여부';

COMMENT ON COLUMN "auto_sync_config"."created_at"
    IS '생성일';

COMMENT ON COLUMN "auto_sync_config"."updated_at"
    IS '수정일';


COMMENT ON COLUMN "sync_job"."index_info_id"
    IS '대상 지수 정보 ID';

COMMENT ON COLUMN "sync_job"."target_date"
    IS '대상 날짜';

COMMENT ON COLUMN "sync_job"."worker"
    IS '요청 IP 또는 SYSTEM';

COMMENT ON COLUMN "sync_job"."job_time"
    IS '작업 일시';

COMMENT ON COLUMN "sync_job"."result"
    IS 'SUCCESS, FAILED';

COMMENT ON COLUMN "sync_job"."created_at"
    IS '생성일';

COMMENT ON COLUMN "sync_job"."updated_at"
    IS '수정일';

COMMENT ON COLUMN "sync_job"."job_type"
    IS 'INDEX_INFO, INDEX_DATA';
